## Simple R/exams example
Here are example files for using R/exams to create autogenerated multiple choice questions. Each Rnw file contains 1 question.

### How to install exams
`install.packages("exams", dependencies = TRUE)` in the console of R studio. 
### How to export to Canvas
1. Define you exam. For these example files you can use this in the console:
`physicalChem <- c("ideellGassLov.Rnw", "vdW.Rnw", "entropi.Rnw")`
2. make QTI-zip:
`exams2canvas(physicalChem, n=10, name=termodynamikk)` n=10 means we make 10 copies of each question.
3. Open Canvas, choose course and navigate to instillinger->importert kursinnhold and then in the dropdown select QTI-zip-fil. Upload the zip (termodynamikk.zip) and either select a spørsmålsbank or select opprett ny spørsmålsbank. Import. 
4. following these steps will create a new quiz called 'termodynamikk' and a new spørsmålsbank 'termodynamikk'.

